### ISSUE TITLE
How to disable virtual disk renaming?

### ISSUE THREAD

**Issue by stroev-ao** [dokan-dev/dokany#1170]
This does not interfere with the operation of the disk, but from a logical point of view, this should not be possible, since the disk name in my case is set remotely.

**Comment by Liryna** [comment]
Sorry I haven't tried it myself from C# but there is indeed a Marshall allocation issue here

**Comment by stroev-ao** [comment]
Can you create an c++ example please?

**Comment by LTRData** [comment]
> I use the InitializeSecurityDescriptor and SetSecurityDescriptorDacl methods from advapi32.dll, get the SECURITY_DESCRIPTOR structure, convert its IntPtr to a byte array and set it to the VolumeSecurityDescriptor field. After that I get an exception when calling DokanBuilder.Build. Am I doing it right?

I would strongly suggest that you use .NET model objects for this as far as possible.

```
        var sec = new FileSecurity();

        sec.AddAccessRule( ... );

        var bytes = sec.GetSecurityDescriptorBinaryForm();

        options.VolumeSecurityDescriptor = bytes;
        options.VolumeSecurityDescriptorLength = bytes.Length;
```

There could of course still be things that you need to call through P/Invoke depending on what you want to do. But in my experience, that is almost never needed.

Does this help in your case?

**Comment by stroev-ao** [comment]
Thanks for the advice @LTRData! I tried to do it in .NET model objects but got the same exception. I also tried not setting a value in the VolumeSecurityDescriptorLength field - doesn't matter.
![image](https://github.com/dokan-dev/dokany/assets/86775842/b9d6c337-838b-4d69-8602-dfc2206bef7d)

**Comment by stroev-ao** [comment]
Sure. Exception type is System.ArgumentException. Message: Type could not be marshaled because the length of an embedded array instance does not match the declared length in the layout. Stack trace:
   at System.StubHelpers.MngdFixedArrayMarshaler.ConvertSpaceToNative(IntPtr pMarshalState, Object& pManagedHome, IntPtr pNativeHome)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Interop.Ole32.CoTaskMemFree(IntPtr ptr)
   at System.Runtime.InteropServices.Marshal.StructureToPtr(Object structure, IntPtr ptr, Boolean fDeleteOld)
   at System.Runtime.InteropServices.Marshal.StructureToPtr[T](T structure, IntPtr ptr, Boolean fDeleteOld)
   at DokanNet.NativeStructWrapper`1..ctor(T obj)
   at DokanNet.NativeStructWrapper.Wrap[T](T obj)
   at DokanNet.DokanInstance..ctor(ILogger logger, DOKAN_OPTIONS options, IDokanOperations operations)
   at DokanNet.DokanInstanceBuilder.Build(IDokanOperations operations)
   at MyClass (where DokanBuilder.Build is called).

What other information might help?

**Comment by LTRData** [comment]
Ah okay I understand. I missed that part. You need to realize the array:
`Array.Resize(ref bytes, 16384);`

**Comment by stroev-ao** [comment]
> Ah okay I understand. I missed that part. You need to resize the array: `Array.Resize(ref bytes, 16384);`

Okay, one more exception. Type: DokanException. Message: Can't install the Dokan driver. Stack trace:
   at DokanNet.DokanInstance..ctor(ILogger logger, DOKAN_OPTIONS options, IDokanOperations operations)
   at DokanNet.DokanInstanceBuilder.Build(IDokanOperations operations)
   at MyClass (where DokanBuilder.Build is called).

Am I doing it right?
![image](https://github.com/dokan-dev/dokany/assets/86775842/d1050c3a-f70a-4a6d-89bf-9bb7b136c2c5)

**Comment by LTRData** [comment]
Have you installed the Dokan setup package? Did you get any errors when you did that? What does the command `sc query dokan2` at command line say?

**Comment by stroev-ao** [comment]
> Have you installed the Dokan setup package? Did you get any errors when you did that? What does the command `sc query dokan2` at command line say?

Yes, the Dokan package installed without errors.
![image](https://github.com/dokan-dev/dokany/assets/86775842/fe554af8-203b-4310-83b7-befc8eb33597)
The command **sc query dokan2** result:
![image](https://github.com/dokan-dev/dokany/assets/86775842/ccd1c49a-7357-4e66-8871-9455f2be1d78)

**Comment by LTRData** [comment]
Strange. Could it be some kind of version mismatch between the native dokan2.dll that gets loaded into your process and Dokan2 driver? I am unsure in this case. It looks like it should have worked.

**Comment by stroev-ao** [comment]
> Strange. Could it be some kind of version mismatch between the native dokan2.dll that gets loaded into your process and Dokan2 driver? I am unsure in this case. It looks like it should have worked.

You were right. The Dokan Library version was 2.0.6.1, the Dokan version from Nuget in my project is 2.0.5.1. I uninstalled Dokan Library 2.0.6.1 then installed Dokan Library 2.0.5.1, but the problem is still there.

**Comment by Liryna** [comment]
If other C# sample work, it means your install is correct but the provided VolumeSecurity are incorrect and failed the mount.

**Comment by LTRData** [comment]
> > Strange. Could it be some kind of version mismatch between the native dokan2.dll that gets loaded into your process and Dokan2 driver? I am unsure in this case. It looks like it should have worked.
> 
> You were right. The Dokan Library version was 2.0.6.1, the Dokan version from Nuget in my project is 2.0.5.1. I uninstalled Dokan Library 2.0.6.1 then installed Dokan Library 2.0.5.1, but the problem is still there.

I see now that this problem happens with that security descriptor if added to the native memfs C sample as well.

```
    PSECURITY_DESCRIPTOR sec_desc;
    ULONG sec_desc_length;
    BOOL rc = ConvertStringSecurityDescriptorToSecurityDescriptor(L"D:(D;;SD;;;WD)", SDDL_REVISION_1, &sec_desc, &sec_desc_length);
    memcpy(dokan_options.VolumeSecurityDescriptor, sec_desc, sec_desc_length);
    dokan_options.VolumeSecurityDescriptorLength = sec_desc_length;
    LocalFree(sec_desc);
````

I'll try to figure out what is going on here.

(Also, please do not post screenshots as pictures here, copy and paste your code instead so that it is easier for others to try out the same thing without the need to type your code manually and risk mistakes. Thank you!)

**Comment by stroev-ao** [comment]
> Okay, so the problem here is that the security descriptor does not allow anything which means that everything is disallowed, which causes dokan2.dll not to be able to open the volume using `CreateFile`. The security descriptor needs to allow something:
> 
> ```
>             var sec = new FileSecurity();
>             sec.AddAccessRule(new FileSystemAccessRule(new SecurityIdentifier(WellKnownSidType.WorldSid, null), FileSystemRights.ReadAndExecute, AccessControlType.Allow));
>             sec.AddAccessRule(new FileSystemAccessRule(new SecurityIdentifier(WellKnownSidType.WorldSid, null), FileSystemRights.Delete, AccessControlType.Deny));
>             var bytes = sec.GetSecurityDescriptorBinaryForm();
> ```
> 
> But actually, you could skip denying delete actions because anything that is not explicitly allowed in this security descriptor will be denied automatically:
> 
> ```
>             var sec = new FileSecurity();
>             sec.AddAccessRule(new FileSystemAccessRule(new SecurityIdentifier(WellKnownSidType.WorldSid, null), FileSystemRights.ReadAndExecute, AccessControlType.Allow));
>             var bytes = sec.GetSecurityDescriptorBinaryForm();
> ```

Great, it works! Thank you! But how to prevent drive renaming but allow all actions with all subdirectories and files? Because all security rights are inherited for all content I cannot rename or delete directories and create files. Ttried to add FileSystemRight.DeleteSubdirectoriesAndFiles. Also tried setting FullControl for all directories and files in the GetFileSecurity method. Another attempt is to use inheritance to all subdirectories and files when adding FileSystemRight.DeleteSubdirectoriesAndFiles. All attempts fail. Can you help me with this? I'm not strong with FileSystemRights yet.

**Comment by stroev-ao** [comment]
I found that the FileSystemRights.WriteData right disables disk renaming when it's denied. But it also prevent files to being created. I tried this but to no avail:
`fileSecurity.AddAccessRule(new FileSystemAccessRule(securityIdentifier, FileSystemRights.WriteData, InheritanceFlags.None, PropagationFlags.None, AccessControlType.Deny));`

**Comment by Liryna** [comment]
@stroev-ao Have you been able to resolve this issue ?

**Comment by stroev-ao** [comment]
> @stroev-ao Have you been able to resolve this issue ?

No, the problem is not solved. The advice above from @LTRData did not help.

**Comment by LTRData** [comment]
> > @stroev-ao Have you been able to resolve this issue ?
> 
> No, the problem is not solved. The advice above from @LTRData did not help.

Like I said in my last comment, this is a more kind of general question not Dokan specific and you might want to search for hints about how to do it in other places. I would assume that you would need to create an ACL with some propagating allow permissions for all users and then some non-propagating deny permissions specifically denying deletion. The inheritance parts of it are most important in this specific case.
