### ISSUE TITLE
AppVeyor CI breakage

### ISSUE THREAD

**Issue by woachk** [dokan-dev/dokany#807]
Sorry for causing that one with the switch to VS2019. :)

It turns out that the CI build fails at updating the toolchain on MSYS2. (log available at https://ci.appveyor.com/project/Maxhy/dokany/branch/master/job/r5arpfiv67if9xwc )

The proper way to fix might be to install MSYS64 directly as a part of the script on the image.

**Comment by Liryna** [comment]
Yeah @woachk I was a little surprised 😆 I can look at it this weekend no worry 😉

**Comment by Rondom** [comment]
We can move to plain MinGW-W64 instead of using the MinGW-W64 shipped by MSYS2 and achieve the same result.

Historically, we had a few problems keeping the build stable in that regard given that MSYS2 is a project with very limited manpower.

@Liryna If you haven't looked into it, then I can have a look, if you want. Care has to be taken to take the right variant (exception handling, threading etc)

**Comment by Liryna** [comment]
@Rondom You can! <3 I will have other stuff to do around dokan for the weekend.

**Comment by woachk** [comment]
@Liryna @Rondom when doing that, I might recommend using https://github.com/mstorsjo/llvm-mingw too.

Self-contained MinGW-w64 build with LLVM, with ARM & ARM64 MinGW support too.

**Comment by Liryna** [comment]
WiX is currently not supporting vs2019.
Have tried to install the Release Candidate VS WiX plugin extension by command line but I get I failure. Manually connected to RDP, install pass and WiX project can be opened.
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VSIXInstaller.exe" /appIdName:VS /skuName:Community /skuVersion:16.0   C:\projects\dokany\dokan_wix\Votive2019.vsix

If anyone has an idea 😢 seems like if find plugin to only support VS 16.0 when we have 16.1.3 installed. (I tried to use skuVersion:16.1 skuVersion:16.1.2)
```
6/22/2019 4:43:10 PM - Microsoft VSIX Installer
6/22/2019 4:43:10 PM - -------------------------------------------
6/22/2019 4:43:10 PM - vsixinstaller.exe version:
6/22/2019 4:43:10 PM - 16.1.3121
6/22/2019 4:43:10 PM - -------------------------------------------
6/22/2019 4:43:10 PM - Command line parameters:
6/22/2019 4:43:10 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,/appIdName:VS,/skuName:Community,/skuVersion:16.0,C:\projects\dokany\dokan_wix\Votive.vsix
6/22/2019 4:43:10 PM - -------------------------------------------
6/22/2019 4:43:10 PM - Microsoft VSIX Installer
6/22/2019 4:43:10 PM - -------------------------------------------
6/22/2019 4:43:10 PM - Initializing Install...
6/22/2019 4:43:11 PM - Extension Details...
6/22/2019 4:43:11 PM - 	Identifier         : WixToolset.VisualStudioExtension.Dev16
6/22/2019 4:43:11 PM - 	Name               : Wix Toolset Visual Studio 2019 Extension
6/22/2019 4:43:11 PM - 	Author             : .NET Foundation and contributors
6/22/2019 4:43:11 PM - 	Version            : 1.0.0.3
6/22/2019 4:43:11 PM - 	Description        : Visual Studio integration for the WiX Toolset - the most powerful set of tools available to create your Windows installation experience.
6/22/2019 4:43:11 PM - 	Locale             : en-US
6/22/2019 4:43:11 PM - 	MoreInfoURL        : http://wixtoolset.org/
6/22/2019 4:43:11 PM - 	InstalledByMSI     : False
6/22/2019 4:43:11 PM - 	SupportedFrameworkVersionRange : [4.0,)
6/22/2019 4:43:11 PM - 
6/22/2019 4:43:11 PM - 	SignatureState     : ValidSignature
6/22/2019 4:43:11 PM - 	SignedBy           : WiX Toolset (.NET Foundation)
6/22/2019 4:43:11 PM - 	Certificate Info   : 
6/22/2019 4:43:11 PM - 		-------------------------------------------------------
6/22/2019 4:43:11 PM - 		[Subject]       : CN=WiX Toolset (.NET Foundation), O=WiX Toolset (.NET Foundation), L=Redmond, S=wa, C=US, SERIALNUMBER=603 389 068
6/22/2019 4:43:11 PM - 		[Issuer]        : CN=.NET Foundation Projects Code Signing CA, O=.NET Foundation, C=US
6/22/2019 4:43:11 PM - 		[Serial Number] : 0D5EF90303C2280377DFE04D74E20861
6/22/2019 4:43:11 PM - 		[Not Before]    : 4/3/2019 12:00:00 AM
6/22/2019 4:43:11 PM - 		[Not After]     : 4/7/2022 12:00:00 PM
6/22/2019 4:43:11 PM - 		[Thumbprint]    : C95FC39334E667F3DD3D82AF382E05719B88F7C1
6/22/2019 4:43:11 PM - 
6/22/2019 4:43:11 PM - 	Supported Products : 
6/22/2019 4:43:11 PM - 		Microsoft.VisualStudio.Community
6/22/2019 4:43:11 PM - 			Version : [16.0,17.0)
6/22/2019 4:43:11 PM - 
6/22/2019 4:43:11 PM - 	References         : 
6/22/2019 4:43:11 PM - 		-------------------------------------------------------
6/22/2019 4:43:11 PM - 		Identifier   : WixToolset.VisualStudioExtension.Schemas3
6/22/2019 4:43:11 PM - 		Name         : WiX Toolset v3 Schemas for Visual Studio
6/22/2019 4:43:11 PM - 		Version      : 
6/22/2019 4:43:11 PM - 		MoreInfoURL  : 
6/22/2019 4:43:11 PM - 		Nested       : Yes
6/22/2019 4:43:11 PM - 
6/22/2019 4:43:11 PM - 		-------------------------------------------------------
6/22/2019 4:43:11 PM - 		Identifier   : WixToolset.VisualStudioExtension.Schemas4
6/22/2019 4:43:11 PM - 		Name         : WiX Toolset v4 Schemas for Visual Studio
6/22/2019 4:43:11 PM - 		Version      : 
6/22/2019 4:43:11 PM - 		MoreInfoURL  : 
6/22/2019 4:43:11 PM - 		Nested       : Yes
6/22/2019 4:43:11 PM - 
6/22/2019 4:43:11 PM - 	Prerequisites      : 
6/22/2019 4:43:11 PM - 		-------------------------------------------------------
6/22/2019 4:43:11 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
6/22/2019 4:43:11 PM - 		Name         : Microsoft.VisualStudio.Component.CoreEditor
6/22/2019 4:43:11 PM - 		Version      : [16.0,17.0)
6/22/2019 4:43:11 PM - 
6/22/2019 4:43:11 PM - Signature Details...
6/22/2019 4:43:11 PM - 	Extension is signed with a valid signature.
6/22/2019 4:43:11 PM - 
6/22/2019 4:43:11 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

```

**Comment by woachk** [comment]
Yeah WiX has to be updated for the 16.1 VS2019 minor update, it's just like that for each VS2017 update too.

**Comment by Liryna** [comment]
@woachk Yes I understand. Just here appveyor do not have the extension installed so we need to do it by command line. Could not make it work :(

**Comment by Liryna** [comment]
Well, I succeed in installing wix vsix and found out right after that tomorrow appveyor image release will have the vsix 😭 
https://github.com/appveyor/ci/issues/2992
BUT Appveyor has WiX 3.11.0 installed and the extension does not seems to work well with this extension
https://github.com/appveyor/ci/issues/2992#issuecomment-504733009

**Comment by Liryna** [comment]
WDK is missing from 2019 image https://github.com/appveyor/ci/issues/2994

**Comment by Liryna** [comment]
ARM / ARM 64 missing https://github.com/appveyor/ci/issues/2995 and Spectre mitigations https://github.com/appveyor/ci/issues/2996

**Comment by Liryna** [comment]
@woachk @Rondom Appveyor has updated the image with needed fix https://ci.appveyor.com/project/Maxhy/dokany/builds/25537263 🚀 we can now fix the build
